[package]
name = "audio-lux"
version = "0.1.0"
authors = ["Tate Allen"]
edition = "2018"

[dependencies]
portaudio = "0.7.0"
rustfft = "3.0.0"
piston = "0.42.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.54.0"
piston2d-opengl_graphics = "0.59.0"
